services: 
  qart:
    image: local/qart
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qart
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
    environment:
      - GIN_MODE=release
